### PR TITLE
search engine preview

### PR DESCRIPTION
**Pull request by alFlash**
It woult be nice to have a live preview for e.g. google search entries. 
1. title
2. link 
3. description ( with max. chars)

All of these in typical style of e.g. google
For our editors it would be a great benefit to have a visualisation for this very important description.

THX so much for your great work.

### CODE REVIEW

**Comment by fabianmichael** [comment]
@alFlash Thanks for your contribution. Though search engines are often generating text and description from actual page content and based on your actual search terms, having a rough idea about how a page might be displayed is still great.

Unfortunately, I cannot merge this PR as it is now. I refactored everything a few days ago and your PR probably started from an older commit and now we got quite a mess. Please cleanup, so only the files that you have actually edited are part of the PR. Git is hard … so it might be easier to create a new branch from `main` and copy the changed files over.

**Comment by alFlash** [comment]
I'm lost in github...

**Comment by fabianmichael** [comment]
@alFlash No worries, I’ve been in a situation like that many times before and I still suck at using git. I’d still be happy to add your search engine preview to the plugin. It was just bad co-incidence, that I refactored so many files after you started working on your branch, which lead to all the problems.

Just one question: Did you actually implement the preview widget, since I cannot find anything in the commits of this pull request … if this was just meant to be a feature request, don’t hesitate to open an **issue** instead.

In case you want to implement it by yourself and make a contribution to the plugin, a **pull request** would be the most adequate form of suggesting code changes/additions. A good starting point might be the [meta knight plugin](https://github.com/diesdasdigital/kirby-meta-knight), which includes such a preview.

**Comment by fabianmichael** [comment]
Closing this due to lack of activity

**Pull request closed without merging**
