### PR TITLE
files section enhancements

### PR DESCRIPTION
**Pull request by bogdancondorachi**
Hi @fabianmichael,

Currently, the files section shows all the images of a page, which is pretty unesthetic and confusing if you got lots of images, braking the right sticky section feel as well.

I've added `template` option to files section to only show the `meta-og-image` files that are relevant to the seo tab.

Also, I've added a bool to the files section in case you want to hide the section completely on pages. It's enabled by default and you can disable it in config through `'fabianmichael.meta.files' => false`.

**WARNING: meta_logo template files won't be shown in the site files field**
Regarding this, I'm thinking that since the twitter og is deprecated, we could remove the twitter size requirement from `meta-og-image` and use a single template for both `meta_logo` and `meta-og-image` as well.

Looking to see what are your thoughts on this.

### CODE REVIEW

**Comment by ghost** [comment]
@bogdancondorachi 💪 very nice!

**Comment by fabianmichael** [comment]
@bogdancondorachi Nice ideas, but I am not sure if the plugin should mess with file blueprints at all. My experience from working with custom file blueprints in Kirby has always been messy, because it is total confusing to have general file sections but not being able to select from of these without any apparent reason in the interface. Should we just consider removing all file blueprints from the plugin?

The logo blueprint was intendend for schema.org markup and not for Twitter cards, so I would not consider it as deprecated.

**Comment by bogdancondorachi** [comment]
@fabianmichael You got a good point. I'm just thinking now as you've said maybe just remove the files section and files blueprints. My problem was with the files section as it looks unesthetic and also unuseful as on all my pages I already integrate a files section or a tab with all the files of a page. So I just don't see the need for one in the meta tabs.

**Comment by fabianmichael** [comment]
@bogdancondorachi The problem arises, when a page does not have any files sections on its own. Editors often struggle with housekeeping anyway and every page that deals with images needs at least one file section.

**Comment by ghost** [comment]
Maybe we could specify the directory (= not necessarily inside `content`) and file template to be used as plugin settings?

**Comment by fabianmichael** [comment]
> Maybe we could specify the directory (= not necessarily inside `content`) and file template to be used as plugin settings?

Where should files be saved if not in the content directory? For my, it’s an obvious choice to save site-specific files within the content directory.

**Comment by ghost** [comment]
Many devs are using `assets` to upload site-related media in order to keep the `content` root clean .. 🤔

**Comment by fabianmichael** [comment]
@CHE1RON That makes sense, but the assets folder is also often used as build target and could possibly be listed in `.gitignore`. And why should a favicon or og image not be treated as content?

**Comment by ghost** [comment]
Don't ask me 🤷 I just suggested it to make it more flexible, brainstorming if you will 😅

**Comment by fabianmichael** [comment]
This has been stale for a while and unfortunately, I currently do not have the time for discussing this any further. Sorry :-(

**Pull request closed without merging**
